import type { NextPage } from "next";
import Head from "next/head";
import ImageUploading, { ImageListType } from "react-images-uploading";
import { useState } from "react";

const Home: NextPage = () => {
    const [images, setImages] = useState<ImageListType>([]);

    const onChange = (
        imageList: ImageListType,
        addUpdateIndex?: number[]
    ): void => {
        // data for submit
        console.log(addUpdateIndex);
        setImages(imageList);
    };

    const handleImageSwap = (
        itemPosOne: number,
        itemPosTwo: number
    ): (() => void) => {
        return (): void => {
            if (!images[itemPosOne] || !images[itemPosTwo]) {
                return;
            }

            const tempItemPosOne = images[itemPosOne];
            const tempImages = [...images];
            tempImages[itemPosOne] = images[itemPosTwo];
            tempImages[itemPosTwo] = tempItemPosOne;

            setImages(tempImages);
        };
    };

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="p-4">
                <div className=" mb-4">
                    <div className="mx-auto h-64 w-64">
                        {images.map((image, index) => (
                            <img
                                src={image.data_url}
                                width="256"
                                className="absolute"
                                key={index}
                                style={{ zIndex: index + 1 }}
                            />
                        ))}
                    </div>
                </div>
                <div>
                    <ImageUploading
                        multiple
                        value={images}
                        onChange={onChange}
                        maxNumber={15}
                        dataURLKey="data_url"
                        acceptType={["png"]}
                    >
                        {({
                            imageList,
                            onImageUpload,
                            onImageRemoveAll,
                            onImageUpdate,
                            onImageRemove,
                            isDragging,
                            dragProps,
                        }) => (
                            // write your building UI
                            <div className="upload__image-wrapper">
                                <button
                                    className={`rounded-full ${
                                        isDragging
                                            ? "bg-slate-500"
                                            : "bg-slate-300"
                                    } px-4 py-2`}
                                    onClick={onImageUpload}
                                    {...dragProps}
                                >
                                    Click or Drop here
                                </button>
                                &nbsp;
                                <button
                                    onClick={onImageRemoveAll}
                                    className="rounded-full bg-slate-100 px-4 py-2"
                                >
                                    Remove all images
                                </button>
                                {imageList.map((image, index) => (
                                    <div key={index} className="mt-4 flex">
                                        <img
                                            src={image.data_url}
                                            alt=""
                                            width="100"
                                            className="mr-2 border-2 border-solid"
                                        />
                                        <div className="flex flex-col justify-center align-middle">
                                            <div className="flex flex-row items-center">
                                                <svg
                                                    xmlns="http://www.w3.org/2000/svg"
                                                    viewBox="0 0 24 24"
                                                    fill="currentColor"
                                                    className="mr-3 h-6 w-6 cursor-pointer"
                                                    onClick={handleImageSwap(
                                                        index - 1,
                                                        index
                                                    )}
                                                >
                                                    <path
                                                        fillRule="evenodd"
                                                        d="M11.47 2.47a.75.75 0 011.06 0l7.5 7.5a.75.75 0 11-1.06 1.06l-6.22-6.22V21a.75.75 0 01-1.5 0V4.81l-6.22 6.22a.75.75 0 11-1.06-1.06l7.5-7.5z"
                                                        clipRule="evenodd"
                                                    />
                                                </svg>
                                                <button
                                                    onClick={() =>
                                                        onImageUpdate(index)
                                                    }
                                                    className="mb-2 bg-slate-100 px-4 py-2"
                                                >
                                                    Update
                                                </button>
                                            </div>
                                            <div className="flex flex-row items-center">
                                                <svg
                                                    xmlns="http://www.w3.org/2000/svg"
                                                    viewBox="0 0 24 24"
                                                    fill="currentColor"
                                                    className="mr-3 h-6 w-6 cursor-pointer"
                                                    onClick={handleImageSwap(
                                                        index,
                                                        index + 1
                                                    )}
                                                >
                                                    <path
                                                        fillRule="evenodd"
                                                        d="M12 2.25a.75.75 0 01.75.75v16.19l6.22-6.22a.75.75 0 111.06 1.06l-7.5 7.5a.75.75 0 01-1.06 0l-7.5-7.5a.75.75 0 111.06-1.06l6.22 6.22V3a.75.75 0 01.75-.75z"
                                                        clipRule="evenodd"
                                                    />
                                                </svg>

                                                <button
                                                    onClick={() =>
                                                        onImageRemove(index)
                                                    }
                                                    className="mb-2 bg-slate-100 px-4 py-2"
                                                >
                                                    Remove
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        )}
                    </ImageUploading>
                </div>
            </div>
        </div>
    );
};

export default Home;
